plugins:
  - simple
  - search
  - mkdocstrings:
      default_handler: python
  - awesome-pages:
      collapse_single_pages: true
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: green
    accent: green
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/althack
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/althack
    - icon: fontawesome/regular/face-laugh
      link: https://allisonthackston.com
  analytics:
    provider: google
    property: G-VPNW28KW9L
  version:
    provider: mike
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
