# This workflow rebuilds docs that use this configuration as a template.
# This ensures that downstream repositories are updated when the configuration changes.
name: Rebuild Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-repos:
    runs-on: ubuntu-latest
    outputs:
      repository: ${{ steps.list.outputs.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get repos list
        id: list
        uses: ./.github/actions/list-repos
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo
        run: echo "The repositories are ${{ steps.list.outputs.repository }}"
  rebuild-docs:
    needs: get-repos
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        repository: ${{ fromJSON(needs.get-repos.outputs.repository) }}
      fail-fast: false
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: ${{ matrix.repository }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: publish-docs
